### ISSUE TITLE
find() freezes system

### ISSUE THREAD

**Issue by step21** [jeroen/mongolite#100]
Hi, so I am guessing this is kind of normal because of some constraints - but maybe you/someone could clarify or confirm or deny.
I was running `m$find()` with `m` being an instantiation of mongolite with `mongo`. This froze up my whole system relatively quickly, with no solutions apart from a hard reboot. This was on Ubuntu 16.04.2 with R 3.4.1, running in R Studio. This was on a fast ssd and with 16 GB Ram. Processor was less good, but I assume anyway that this operation was not CPU bound.
`m` here was connected to a local mongodb server with one database and collection of about 3.4 Million documents. So would be great if you could say if that is expected behaviour and how to maybe avoid this if I just want to run find for testing or something...

**Comment by a-n-d-r-e-i** [comment]
@step21 Reduce `pagesize` argument could help you in this case. If you reduce that to, say, 100, then I expect the operation to take more time, but at least wouldn't freeze your system. However, I'm not sure if that makes sense. Can you try and get back to us?

**Comment by step21** [comment]
Sure, I will investigate. If I recall, I didn't give any pagesize argument.

**Comment by jeroen** [comment]
Did you solve this problem? Also have a look at [mongolite iterator](https://jeroen.github.io/mongolite/query-data.html#iterating) to incrementally process large data.

**Comment by step21** [comment]
I think it was fine with pagesize, in the end it was infeasible to use R for me anyway. Thanks for following up.
