### ISSUE TITLE
Invalid JSON object

### ISSUE THREAD

**Issue by toncek87** [jeroen/mongolite#101]
I'd like to get data from my mongo greater/lower than UnixTimestamp. I tried two options

`test <- con$find('{"project":"31" , "{"created":"{"$gt":1500129409}"}}"')`
  
`test <- con$find('{"project":"31" , "created":{$gt:1500129409}}')`

where is fault? thank you

**Comment by SymbolixAU** [comment]
see 
https://stackoverflow.com/q/34454034/5977215
and
https://stackoverflow.com/q/36562894/5977215

**Comment by toncek87** [comment]
this works con$find('{"project":"1","created":{"$lt":1498867200}}')
