### ISSUE TITLE
error: unknown type name ‘size_t’

### ISSUE THREAD

**Issue by toncek87** [jeroen/mongolite#102]
during the installation on Debian 8. Jessie

In file included from mongoc/mongoc-cluster-sasl.c:21:0:
/usr/local/include/sasl/sasl.h:230:38: error: unknown type name ‘size_t’
 typedef void *sasl_realloc_t(void *, size_t);
                                      ^
/usr/local/include/sasl/sasl.h:235:5: error: unknown type name ‘sasl_realloc_t’
     sasl_realloc_t *,
     ^
/usr/lib/R/etc/Makeconf:132: recipe for target 'mongoc/mongoc-cluster-sasl.o' failed
make: *** [mongoc/mongoc-cluster-sasl.o] Error 1
ERROR: compilation failed for package ‘mongolite’
* removing ‘/home/rko/R/x86_64-pc-linux-gnu-library/3.3/mongolite’

Session info -------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2017-07-27                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------
 package  * version date       source        
 curl       1.2     2016-08-13 cran (@1.2)   
 devtools * 1.12.0  2016-06-24 CRAN (R 3.2.5)
 digest     0.6.12  2017-01-27 cran (@0.6.12)
 git2r      0.15.0  2016-05-11 CRAN (R 3.2.5)
 httr       1.2.1   2016-07-03 CRAN (R 3.3.1)
 knitr      1.14    2016-08-13 CRAN (R 3.3.1)
 magrittr   1.5     2014-11-22 CRAN (R 3.2.5)
 memoise    1.0.0   2016-01-29 CRAN (R 3.2.5)
 R6         2.2.0   2016-10-05 cran (@2.2.0) 
 stringi    1.1.2   2016-10-01 cran (@1.1.2) 
 stringr  * 1.1.0   2016-08-19 cran (@1.1.0) 
 withr      1.0.2   2016-06-20 CRAN (R 3.2.5)

**Comment by jeroen** [comment]
Which version of mongolite are you installing? Also please do:

```r
update.packages(ask=F, checkBuilt=T)
```

**Comment by toncek87** [comment]
i used install_github("jeroen/mongolite")

**Comment by toncek87** [comment]
i've updated all of my libraries and error still exists...

**Comment by jeroen** [comment]
I think this might be a bug in either debian `libsasl` headers or mongo-c-driver. The error appears when immediately at `#include <sasl/sasl.h>` when compiling `mongoc-cluster-sasl.c`.

**Comment by jeroen** [comment]
Actually it looks like you have a broken version of sasl on your system. Your compiler is including:

```
/usr/local/include/sasl/sasl.h
```

Stuff in `/usr/local` is usually built from source. Try removing libsasl from `/usr/local/include/sasl` and `/usr/local/lib/` and instead just use the stock version:

```
sudo apt-get install -y libssl-dev libsasl2-dev 
```

**Comment by toncek87** [comment]
removing libsasl  - do you mean hard delete from folders? i tried `apt-get remove libsasl` and nothing happend (Unable to locate package libsasl)

**Comment by toncek87** [comment]
haha it works :-) .. hard delete libsasl folders from directories /usr/local/include and /usr/local/lib and works. thanks
