### ISSUE TITLE
Is possible to support connection pool?

### ISSUE THREAD

**Issue by smartguo** [jeroen/mongolite#104]
Hi, first of all - thanks for your excellent work! 
As I use this package in my work, it does a great job! But there is a problem shooting me that opening and closing connections frequently costs a lot. So I look up the documentation for a solution but it seems that connection pool is not supported yet. Is there any chance to support this feature or any other solution?
Thank you!

**Comment by jeroen** [comment]
This is now added in master (soon on cran).
