### ISSUE TITLE
How to install on FreeBSD? Problem with SYS_gettid

### ISSUE THREAD

**Issue by sztal** [jeroen/mongolite#106]
Is there any chance for installing `mongolite` on FreeBSD? Compilation fails due to the fact that FreeBSD has no `gettid` functionality so `syscall (SYS_gettid);` fails with `error: 'SYS_gettid' undeclared`.

Usage of `SYS_gettid` seems to be a major problem in regard to the package's portability. Or maybe there is some easy way of fixing this that I do not see?

I will soon add the full installation log (have no access to my FreeBSD server at the moment).

**Comment by jeroen** [comment]
I think we need to undef `BSON_HAVE_SYSCALL_TID` for freeBSD inside [bson-config.h](https://github.com/jeroen/mongolite/blob/master/src/bson/bson-config.h)

**Comment by sztal** [comment]
So if I undef it and recompile, then the installation should run?

**Comment by jeroen** [comment]
Fixed via https://github.com/jeroen/mongolite/commit/62a0d5988c03805e63ae86a5db093b3e10dbea8b
