### ISSUE TITLE
Request return type as JSON instead of data.frame

### ISSUE THREAD

**Issue by xiaodaigh** [jeroen/mongolite#109]
I think I am encountering bugs when return as data.frame see #108. It might be due to the jsonlite package not parsing "ill-formed" json properly.

Can we implement a feature in mongolite so that the return type is json and not data.frame, to allow the user to do some self parsing.

**Comment by SymbolixAU** [comment]
I agree this would be a useful addition. 

I made a fork to do something similar, where you can specify `ndjson = T` in `find()` and `aggregate()` functions to return raw ndjson to the user. 

On my github page the two files I've edited are
- R/stream.R : https://github.com/SymbolixAU/mongolite/blob/master/R/stream.R#L71
- R/mongo.R 
  - https://github.com/SymbolixAU/mongolite/blob/master/R/mongo.R#L169
  - https://github.com/SymbolixAU/mongolite/blob/master/R/mongo.R#L204

**Comment by jeroen** [comment]
Can you try if using a [mongolite iterator](https://jeroen.github.io/mongolite/query-data.html#iterating) solves the problem?

**Comment by Jax89** [comment]
I played around with the itterator and if I'm not mistaken, the iterator also gives me a dataframe for the individual iterator elements. Of course its possible to convert it back into json with a jsonlite::toJson but would be much faster if there would be an option to just get raw json.

**Comment by jeroen** [comment]
The iterator gives lists, not a data frame.

**Comment by Jax89** [comment]
Sorry, yes you are right, lists. However it does not change the issue.

**Comment by jeroen** [comment]
MongoDB does not have json but bson internally. So returning json would still involve a conversion.

**Comment by jeroen** [comment]
OK I have added a `json()` method to the iterate class so you can get results as json strings instead of R lists.

**Comment by carlsonp** [comment]
Can you provide a simple example of where/how to pass this parameter?  I see [your commit](https://github.com/jeroen/mongolite/commit/fb88835e8ffa06f9952f70dc4602f4e3e8d39e31) but I'm not quite sure where to pass it.  Thanks

**Comment by Jax89** [comment]
@carlsonp 
pretty straight forward usage:

`iter <- connection$iterate("{}") #gets all documents of the collection the mongodb connection points to`
 
`vectorOfJSON <- iter$json() #return a char vector if jsons`


Works like excpected. 

Is there any way to use the iterator for aggregate pipelines as well?

**Comment by jeroen** [comment]
See https://github.com/jeroen/mongolite/issues/52#issuecomment-411560956

**Comment by SymbolixAU** [comment]
I know you just closed this, but, in addition, the reason I use the `ndjson` return type is so the raw json can be used in `geojsonsf::geojson_sf()` to convert it directly to an `sf` object.

**Comment by jeroen** [comment]
Yes you can get the data as json now by getting the result as an iterator.

**Comment by jeroen** [comment]
By the way can you give an example of how you use json data from mongo with sf?

**Comment by SymbolixAU** [comment]
Sure - I primarily use it with GeoJSON 


```r


library(mongolite)
library(geojsonsf)
library(sf)

sf <- st_read(system.file("shape/nc.shp", package="sf"))

geojson <- geojsonsf::sf_geojson(sf, atomise = T)  

m <- symbolix.utils::connectToMongo(db = "test", collection = "geojson", usr = "db_user")

m$insert(geojson)
m$index((add = '{"geometry" : "2dsphere"}'))

res <- m$find(ndjson = T)

str(res)
# chr [1:100] "{ \"type\" : \"Feature\", \"properties\" : { \"AREA\" : 0.114, \"PERIMETER\" : 1.442, \"CNTY_\" : 1825, \"CNTY_"| __truncated__ ...

sf_res <- geojsonsf::geojson_sf(res)

str(sf_res)
# Classes ‘sf’ and 'data.frame':	100 obs. of  15 variables:
# 	$ AREA     : num  0.114 0.061 0.143 0.07 0.153 0.097 0.062 0.091 0.118 0.124 ...
# $ BIR74    : num  1091 487 3188 508 1421 ...
# $ BIR79    : num  1364 542 3616 830 1606 ...
# $ CNTY_    : num  1825 1827 1828 1831 1832 ...
# $ CNTY_ID  : num  1825 1827 1828 1831 1832 ...
# $ CRESS_ID : num  5 3 86 27 66 46 15 37 93 85 ...
# $ FIPS     : chr  "37009" "37005" "37171" "37053" ...
# $ FIPSNO   : num  37009 37005 37171 37053 37131 ...
# $ NAME     : chr  "Ashe" "Alleghany" "Surry" "Currituck" ...
# $ NWBIR74  : num  10 10 208 123 1066 ...
# $ NWBIR79  : num  19 12 260 145 1197 ...
# $ PERIMETER: num  1.44 1.23 1.63 2.97 2.21 ...
# $ SID74    : num  1 0 5 1 9 7 0 0 4 1 ...
# $ SID79    : num  0 3 6 2 3 5 2 2 2 5 ...
# $ geometry :sfc_MULTIPOLYGON of length 100; first list element: List of 1
# ..$ :List of 1
# .. ..$ : num [1:27, 1:2] -81.5 -81.5 -81.6 -81.6 -81.7 ...
# ..- attr(*, "class")= chr  "XY" "MULTIPOLYGON" "sfg"
# - attr(*, "sf_column")= chr "geometry"

## and compare to the original `sf` object
str(sf)
# Classes ‘sf’ and 'data.frame':	100 obs. of  15 variables:
# 	$ AREA     : num  0.114 0.061 0.143 0.07 0.153 0.097 0.062 0.091 0.118 0.124 ...
# $ PERIMETER: num  1.44 1.23 1.63 2.97 2.21 ...
# $ CNTY_    : num  1825 1827 1828 1831 1832 ...
# $ CNTY_ID  : num  1825 1827 1828 1831 1832 ...
# $ NAME     : Factor w/ 100 levels "Alamance","Alexander",..: 5 3 86 27 66 46 15 37 93 85 ...
# $ FIPS     : Factor w/ 100 levels "37001","37003",..: 5 3 86 27 66 46 15 37 93 85 ...
# $ FIPSNO   : num  37009 37005 37171 37053 37131 ...
# $ CRESS_ID : int  5 3 86 27 66 46 15 37 93 85 ...
# $ BIR74    : num  1091 487 3188 508 1421 ...
# $ SID74    : num  1 0 5 1 9 7 0 0 4 1 ...
# $ NWBIR74  : num  10 10 208 123 1066 ...
# $ BIR79    : num  1364 542 3616 830 1606 ...
# $ SID79    : num  0 3 6 2 3 5 2 2 2 5 ...
# $ NWBIR79  : num  19 12 260 145 1197 ...
# $ geometry :sfc_MULTIPOLYGON of length 100; first list element: List of 1
# ..$ :List of 1
# .. ..$ : num [1:27, 1:2] -81.5 -81.5 -81.6 -81.6 -81.7 ...
# ..- attr(*, "class")= chr  "XY" "MULTIPOLYGON" "sfg"
# - attr(*, "sf_column")= chr "geometry"
# - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
# ..- attr(*, "names")= chr  "AREA" "PERIMETER" "CNTY_" "CNTY_ID" ...
```

**Comment by SymbolixAU** [comment]
Yes that works. My only concern is having to specify the `size` parameter to be the size of your query. Or, having to iterate and `c()` the json together

**Comment by jeroen** [comment]
Under the hood, the `find()` methods iterates through the result, and in the end combines everything together and them simplifies it. With `iterate()` you can control this yourself.

**Comment by jeroen** [comment]
Maybe you like the `export()` method better? You could also do this all in memory:

```r
con <- rawConnection(raw(), 'wb')
m$export(con)
json <- rawToChar(rawConnectionValue(con))
```

**Comment by SymbolixAU** [comment]
I'll run some tests & benchmarks and let you know how I get on. 

Thanks!

**Comment by SymbolixAU** [comment]
I see little difference between the `ndjson` and the `iterate` methods. Possibly the `iterate` is slightly quicker each time I've run the test. But, I still can't see a way around having to know the `size` parameter in `iter$json(size)` prior to running the query. 

```r
library(microbenchmark)

n <- 1e5
microbenchmark(
	iterate = {
		iter <- m$iterate(limit = n)
		iter_res <- iter$json(n)
		iter_sf <- geojsonsf::geojson_sf(iter_res)
	},
	ndjson = {
		nd_res <- m$find(limit = n, ndjson = T)
		nd_sf <- geojsonsf::geojson_sf(nd_res)
	},
	times = 5
)

# Unit: seconds
#    expr      min       lq     mean   median       uq      max neval
# iterate 10.87151 11.27717 11.22539 11.30653 11.31616 11.35557     5
#  ndjson 12.36161 12.54236 12.67818 12.69738 12.73205 13.05752     5
```

I think they are similar because I've made the `find()` method by-pass the `mongo_stream_in()` function when using ndjson:

 - [stream ndjson](https://github.com/SymbolixAU/mongolite/blob/master/R/stream.R#L71)

```r
    find <- function(query = '{}', fields = '{"_id":0}', sort = '{}', skip = 0, limit = 0, handler = NULL, pagesize = 1000, ndjson = FALSE){
      check_col()
      cur <- mongo_collection_find(col, query = query, sort = sort, fields = fields, skip = skip, limit = limit)
      if(ndjson == T){
        ndjson(cur)
      }else{
        mongo_stream_in(cur, handler = handler, pagesize = pagesize, verbose = verbose)
      }
    }
```

 - [find ndjson](https://github.com/SymbolixAU/mongolite/blob/master/R/mongo.R#L171)

```r
ndjson <- function(cur){
  count <- 0;
  pagesize <- 100
  res <- character(0)
  repeat {
    page <- mongo_cursor_next_json(cur, n = pagesize)
    size <- length(page)
    res <- c(res, page)
    count <- count + size;
    if(length(page) < pagesize)
      break
  }
  return(res)
}
```

I didn't include the `export()` method because I can't see a way to pass a `query` into the function.

**Comment by jeroen** [comment]
@SymbolixAU 

> I didn't include the export() method because I can't see a way to pass a query into the function.

I have also exposed that parameter now in `export()` in case you find that useful.
