### ISSUE TITLE
$slice command does not work with Mongolite

### ISSUE THREAD

**Issue by whatthefee** [jeroen/mongolite#115]
The $slice command does not work when referencing arrays in Mongolite. For example a request which works in Robo such as

`mg1$find(query = '{"metaData.key": "123"}', fields = '{"time": 1,"location": 1, "metaData":{$slice:3}}')`
will return an error in Rstudio 
`Error: Invalid JSON object: {"projection":{"time": 1,"location": 1, "metaData":{$slice:3}},"sort":{},"skip":0,"limit":0,"noCursorTimeout":false}`

**Comment by jeroen** [comment]
That doesn't look like valid json. Did you try:

```
query = '{"metaData.key": "123"}', fields = '{"time": 1,"location": 1, "metaData":{ "$slice" : 3}}}'
mg1$find(query = query)
```

**Comment by whatthefee** [comment]
Ah I see. Thanks for clearing that up. Have only been using Mongo for a week so a bit iffy on the technicalitys
