### ISSUE TITLE
Broken backwards compatibility? update appends unknown arrayFilters argument irrespective of mongodb version

### ISSUE THREAD

**Issue by rfhb** [jeroen/mongolite#116]
Continuous integration of my project with mongodb 3.2 triggers the error: 

`Unrecognized field in update operation: arrayFilters`, 

see [https://travis-ci.org/rfhb/ctrdata/jobs/320570386#L1772](https://travis-ci.org/rfhb/ctrdata/jobs/320570386#L1772). 

I wonder if 

` BSON_APPEND_ARRAY (&opts, "arrayFilters", filters);`

in [https://github.com/jeroen/mongolite/blob/master/src/collection.c#L76](https://github.com/jeroen/mongolite/blob/master/src/collection.c#L76) should _not_ be appended if the mongodb version is lower than 3.6, considering that such versions are still used. Thank you.

**Comment by jeroen** [comment]
Ah that is certainly not intended. I have [pushed a fix](https://github.com/jeroen/mongolite/commit/3e8c5edcacd7d46a255a8127217c70532b797b3b) can you try installing the devel version?

```
devtools::install_github("jeroen/mongolite")
```

Thanks for reporting.

**Comment by rfhb** [comment]
Great stuff, works for me and closes #118. Many thanks.

**Comment by rfhb** [comment]
Great, thank you, works well for me and addresses my issue. (My feedback here from 24 Dec seems to have gone, apologies.)
