### ISSUE TITLE
Unable to install: missing zlib.h file

### ISSUE THREAD

**Issue by rodgersk410** [jeroen/mongolite#119]
I'm not able to install this package.  Compilation fails due to what looks like a missing file referenced in mongoc-compression.o

>install.packages("mongolite")
...
mongoc/mongoc-compression.c:26:18: fatal error: zlib.h: No such file or directory
compilation terminated.
make: *** [mongoc/mongoc-compression.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.2/share/make/winshlib.mk" SHLIB="mongolite.dll" OBJECTS="bson.o client.o collection.o cursor.o hex.o mongo_log.o reader.o utils.o"' had status 2
ERROR: compilation failed for package 'mongolite'

**Comment by jeroen** [comment]
Try installing `zlib-dev` for your platform. If you need more help, please include your `sessionInfo()` and full build log.

**Comment by f0nzie** [comment]
Installing `libz-dev` fixes the error. In Debian use  `apt-get -y install  libz-dev`.
This problem doesn't present in Linux physical machines but pops up while building Docker containers.
