### ISSUE TITLE
Remove mongolab references

### ISSUE THREAD

**Issue by rlondner** [jeroen/mongolite#120]
Would it be possible to replace the mongolab connection strings with MongoDB Atlas connection strings?

The relevant files are the following:
- https://github.com/jeroen/mongolite/blob/master/readme.md
- https://github.com/jeroen/mongolite/blob/master/R/mongo.R
- https://jeroen.github.io/mongolite/connecting-to-mongodb.html
- https://cran.r-project.org/web/packages/mongolite/mongolite.pdf
- https://ropensci.org/blog/2017/03/10/mongolite/

Thank you,
Raphael.

**Comment by jeroen** [comment]
This is fixed in mongolite 2.0.
