### ISSUE TITLE
Problem with very large collections

### ISSUE THREAD

**Issue by sergiocalde94** [jeroen/mongolite#121]
Hi!

I am doing a simple find in a collection contains 3 fields, one of then is an array of objects. When I limit the query only to a few of registers all is good, but when I try to query all collections _mongolite_ gives me an error: 

`mongo_conn$find(query = '{}', field = '{}')`
`Error: Unimplemented BSON type 6`

I think that the error really is 'no memory' or something like that, isn´t it?

**Comment by jeroen** [comment]
Hmm I doubt it. Sure there is no strange binary data in your dB?

**Comment by jeroen** [comment]
Did you perhaps upgrade mongodb after inserting data with an old version of mongodb?

**Comment by sergiocalde94** [comment]
Wow, you got it!

There were some corrupt data in the database, I close the issue!

**Comment by ramkumar-equinix** [comment]
@sergiocalde94  can you please provide more info, what type of of corrupted data, and how you found it

**Comment by sergiocalde94** [comment]
This is from 4 years ago! I don't remember but I think that was something related to mongo version.
