### ISSUE TITLE
Custom handlers

### ISSUE THREAD

**Issue by dselivanov** [jeroen/mongolite#125]
Hi Jeroen. Thanks for amazing work. There are couple of issues with custom handlers:

1. there is no documentation about how to use them
1. according to the [source code](https://github.com/jeroen/mongolite/blob/91ecd63bdb8483894a118024ba8f101d4a7b5650/R/stream.R#L43)`mongo_stream_in` always performs post processing and coercion to a data.frame

Is it possible to skip these steps and return each record just as a list?

**Comment by jeroen** [comment]
I think what you want is an iterator: https://jeroen.github.io/mongolite/query-data.html#iterating

**Comment by dselivanov** [comment]
Oh, sorry, missed that. Perfect!
