### ISSUE TITLE
Get information from GridFS

### ISSUE THREAD

**Issue by FidelCastillo** [jeroen/mongolite#127]
hi, I'm tring to use the GridFS functions, and I'm pretty sure that I'm doing something wrong.

This is the pymongo code that I'm tring to replicate in mongolite:

```py
client[ = MongoClient()
db = client['MotorCalculo']
fs = GridFS(db, collection='MotorCalculo')

DF = list()


for grid_out in fs.find({ 'metadata.CodKey':'123'}, no_cursor_timeout = True):
    info = json.loads(grid_out.read().decode())
    DF.append(info['NameCol'])`
```

and this is the mongolite code that  I'm using

```r
conFiles <- mongo('MotorCalculo.files', 'MotorCalculo')
gridFS <- gridfs("MotorCalculo")
gridFS$list(filter = '{"metadata.CodKey":"123"}')`
```

but I'm not able to read the gridFs out file

I have this
```
> gridFS$list(filter = '{"metadata.CodKey":"123"}')
[1] date
<0 rows> (or 0-length row.names)
```

thanks in advance

**Comment by jeroen** [comment]
That seems correct. Do you see anything if you do not pass the filter argument?

**Comment by jeroen** [comment]
What exactly does your metadata look like? This seems to work for me:

```r
# some example data
fs <- mongolite::gridfs("test")
fs$write('iris', serialize(iris, NULL), metadata = '{"author": "jeroen"}')
fs$write('mtcars', serialize(mtcars, NULL), metadata = '{"author": "jimmy"}')
fs$write('cars', serialize(cars, NULL), metadata = '{"author": "jimmy"}')

# shows files with author jimmy
fs$find('{"metadata.author": "jimmy"}')

# drop example data
fs$drop()
```

Are you sure you are using the correct db? What do you get for `fs$find()` without filters?

**Comment by FidelCastillo** [comment]
Sorry I've got a few days off of my work. On Monday l'll be there. But I think that I can get the data from the gridFS

**Comment by francisliyy** [comment]
Hi, why I can't use "fs <- mongolite::gridfs("test")", it says "Error: 'gridfs' is not an exported object from 'namespace:mongolite'

**Comment by jeroen** [comment]
You need the development version of the package:

```r
devtools::install_github("jeroen/mongolite")
```

**Comment by francisliyy** [comment]
I got this error:

ERROR: configuration failed for package ‘mongolite’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/mongolite’
Installation failed: Command failed (1)

**Comment by jeroen** [comment]
You need to give more output.

**Comment by jeroen** [comment]
The CRAN version now has gridfs support so you no longer need to build from source:

```r
install.packages("mongolite")
```
