### ISSUE TITLE
Mongolite connection just stop working.

### ISSUE THREAD

**Issue by gliesian-llc** [jeroen/mongolite#128]
'had mongolite working just fine, and then this happened:

Error: No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on 'localhost:27017']

I tried to fix this for several hours... so I'm asking here for help... is this a mongolite issue... or an external issue?

Thanks,
Robert

**Comment by jeroen** [comment]
This usually means your server is down. Did this happen while you were using mongolite? And you are unable to reconnect?
