### ISSUE TITLE
Documentation: where do I find infos on handlers?

### ISSUE THREAD

**Issue by Ploulackk** [jeroen/mongolite#130]
Hello,

thank you for the work, I use it everyday :)
I'd like to learn more about handlers, and couldn't find anything in the documentation. Could you share a pointer?
Thank you.

**Comment by jeroen** [comment]
What kind of handlers? Which function?

**Comment by Ploulackk** [comment]
the 'find' method as in:
`db$find('{}', handler = )`

**Comment by jeroen** [comment]
Ah OK. It's a callback function, similar to the handler argument in jsonlite::stream_in.

**Comment by Ploulackk** [comment]
Thank you.
Got it. So I can apply my _handler_ function on each page which' size depends on my pagesize parameter. Correct? Talking about this, where could I find more info on the pagesize parameter (still the find method)? Is it per documents found? per actual json lines?

**Comment by jeroen** [comment]
In the mongolite `$find` method it is the number of documents per page. Just try this:

```r
con <- mongo("mtcars", url = "mongodb://readwrite:test@ds043942.mongolab.com:43942/jeroen_test")
con$insert(mtcars)
handler <- function(x){
  cat("found", nrow(x), "documents!\n")
  print(x)
}
con$find("{}", handler = handler, pagesize = 5)
con$drop()
```

**Comment by Ploulackk** [comment]
Great thank you! :)
I've just made my first handler for find. Life feels so much modular suddenly :)

**Comment by jeroen** [comment]
Also have a look at the `iterate` method which is similar but more low-level (per document).
