### ISSUE TITLE
undefined symbol: _mongoc_linux_distro_scanner_get_distro

### ISSUE THREAD

**Issue by jet456** [jeroen/mongolite#132]
Hi,

I'm installing mongolite on R 3.4.0, CentOS 7 (Linux), and am running into the issue below. I've confirmed that all prerequisite packages (openssl-devel and cyrus-sasl-devel) are installed to the system, and have tried installing mongolite via CRAN and source.

Thanks-

```
> install.packages("/apps/R-3.4.0/bin/mongolite.tar.gz", repos=NULL, type="source")
* installing *source* package ‘mongolite’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lsasl2 -lssl -lcrypto   -lresolv
SASL does not have sasl_client_done.
Compiling with extra alignment.
** libs
gcc -std=gnu99 -I/apps/R-3.4.0/lib64/R/include -DNDEBUG -I. -Ijsonsl -Ibson -Imongoc -DBSON_COMPILATION -DMONGOC_COMPILATION -DBSON_EXTRA_ALIGN  -I/usr/local/include   -fpic  -I/apps/zlib-1.2.8/include -I/apps/curl-7.49.1/include/curl -I/apps/bzip2-1.0.6/include -I/apps/xz-5.2.2/include -I/apps/pcre-8.39b/include -I/apps/mpfr-3.1.5/include  -c bson.c -o bson.o
```

{ Lots of compiling output }

```
installing to /apps/R-3.4.0/lib64/R/library/mongolite/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘mongolite’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/apps/R-3.4.0/lib64/R/library/mongolite/libs/mongolite.so':
  /apps/R-3.4.0/lib64/R/library/mongolite/libs/mongolite.so: undefined symbol: _mongoc_linux_distro_scanner_get_distro
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/apps/R-3.4.0/lib64/R/library/mongolite’
Warning message:
In install.packages("/apps/R-3.4.0/bin/mongolite.tar.gz",  :
  installation of package ‘/apps/R-3.4.0/bin/mongolite.tar.gz’ had non-zero exit status
>
```

**Comment by jeroen** [comment]
Which version is this? Can you try installing the development version:

```r
devtools::install_github("jeroen/mongolite")
```

**Comment by jet456** [comment]
I've tried that, and have also tried:
`install.packages("mongolite")`

Same error each time.

**Comment by jeroen** [comment]
Can you show me the full output of `devtools::install_github("jeroen/mongolite")` please?

**Comment by jet456** [comment]
Sure-- thank you for looking into this.
[devtoolsOutput.txt](https://github.com/jeroen/mongolite/files/1925282/devtoolsOutput.txt)

**Comment by jet456** [comment]
$OSTYPE is linux-gnu.

**Comment by jeroen** [comment]
That's strange it should match the regex. Does it work when you remove [this line](https://github.com/jeroen/mongolite/blob/master/configure#L117) from the configure file?

**Comment by jet456** [comment]
Apologies for the late response. Here is what I did:

```
wget https://cran.r-project.org/src/contrib/mongolite_1.5.tar.gz
tar xvzf mongolite-1.5.tar.gz
cd mongolite
vi configure
# here I removed the entire if/fi statement from around line 117, write-quit
./R
```
In R:
```
> install.packages("/apps/R-3.4.0/bin/mongolite-1.5.tar.gz", repos=NULL, type="source")
```

And it worked! The library will load with library(mongolite) now. Thanks again!

**Comment by jeroen** [comment]
OK but that doesn't explain why this happens. Could you modify the `configure` script to `echo $OSTYPE` around line 117? Also do you know what shell your configure script runs in? Just bash?

**Comment by vjcitn** [comment]
I ran into this also.  My centos system responds "Linux".  Removing the lines in configure allowed installation.

**Comment by vjcitn** [comment]
Ran into this again.  As above: removing the lines in configure for mongolite 2.2.1 for "prevent compiler warning for empty unit" permitted installation for a centos system returning "Linux" for $OSTYPE.  Just for the record.
