### ISSUE TITLE
Mongolite Map/Reduce getting Error

### ISSUE THREAD

**Issue by psramkumar** [jeroen/mongolite#134]
Mongo Console it works fine as below
```
var _mapper = function(){emit(this._id, {user_id : this.user_id, name : this.user_name});}
var _reducer = function(id, docs) { return docs; } 
db.user.mapReduce(_mapper, _reducer, { "out": { "inline": 1 } });
```

in R console it is not working and showing the below Error
`**Error: Unimplemented BSON type 6**`

here is the R Snippet
```
user_map<- dbs$mapreduce(
    map = 'function(){emit(this._id, {user_id : this.user_id,name : this.user_name});}',
    reduce = 'function (id, docs) { return docs; }' 
)
```

**Comment by jeroen** [comment]
Your database is probably corrupt. It returns [BSON type 6](https://docs.mongodb.com/manual/reference/bson-types/) data which is undefined/deprecated.

**Comment by psramkumar** [comment]
thanks for your Quick answer,
i tried the below three query with the fields involved in my MR and found no record..
if there any other way i could try ?
```
db.user.find({ _id: { $type: 6 } })
db.user.find({ user_name: { $type: 6 } })
db.user.find({ user_id: { $type: 6 } })
```

**Comment by jeroen** [comment]
Maybe you can use the [aggregate](https://jeroen.github.io/mongolite/calculation.html#aggregate) function.

**Comment by psramkumar** [comment]
my use case is different, going with this way to avoid unwind and multiple pipes of grouping  and so on

thanks :)
