### ISSUE TITLE
Looking for document to show sample about "Finilize" in MongoBD MR

### ISSUE THREAD

**Issue by psramkumar** [jeroen/mongolite#136]
hi i'm looking for option to add finalize method in MongoDB MR thru Mongo Lite 

could some one guide me how to achieve this in Mongolite..

you can find the eample here 
https://stackoverflow.com/questions/5623626/mongodb-mapreduce-iterate-through-objects-key-value-pairs?rq=1

**Comment by jeroen** [comment]
I don't fully understand your question, but the mongo book has [examples](https://jeroen.github.io/mongolite/calculation.html#mapreduce) on how to do map-reduce in mongolite.
