### ISSUE TITLE
decimals rounding issue

### ISSUE THREAD

**Issue by tomfid1983** [jeroen/mongolite#137]
Hi,

there's a problem of incorrect decimal numbers import to R.

Therefore I've got a question if it's possible to implement an appropriate option similar to bigint_as_characters like you introduced dealing with an integer import "issue" here: https://github.com/jeroen/mongolite/issues/77

Thanks!

**Comment by jeroen** [comment]
I don't understand the question. You need to provide example code and data, and explain what you mean by "there is a problem...".
