### ISSUE TITLE
Why can not I install mongolite packages from CRAN?

### ISSUE THREAD

**Issue by ChangMinSeung** [jeroen/mongolite#143]
> install.packages("mongolite")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mongolite_1.6.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mongolite_1.6.zip': HTTP status was '502 Bad Gateway'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mongolite_1.6.zip'
Warning in install.packages :
  download of package ‘mongolite’ failed

**Comment by ChangMinSeung** [comment]
i solve this issue.
options(repos = 'https://cran.asia')
install.packages("mongolite")

thanks.

**Comment by seonghobae** [comment]
All of CRAN mirrors can not find out some library files with specified version number. Although the CRAN.ASIA also try to find out if specified version is not available, especially syncing with CRAN master server. 

Best,
Seongho (CRAN.ASIA Administrations group)
