### ISSUE TITLE
finding nested fields

### ISSUE THREAD

**Issue by ericpgreen** [jeroen/mongolite#157]
Let's say I have a collection called `myCollection` that looks like this:

```
_id: "something"
fieldA: 0
object1: Object
     nestedObject1: Object
          fieldB: 0
          fieldC: 1
fieldD: 1
object2: Object
     nestedObject2: Object
          fieldE: 0
          fieldF: 1
```

How can I use `find()` to get a dataframe of fieldA, fieldB, and fieldC? I'm very new to Mongo, and I'm not quite sure how to make a reproducible example. Sorry!

**Comment by ericpgreen** [comment]
My approach so far has been:

```
df <- myCollection$find(fields = '{"fieldA": true, "nestedObject1": true}')
```

But it gives a dataframe of 3 variables:

- _id: ...
- fieldA: ...
- object1: `data.frame`: 10000 obs. of 0 variables

**Comment by ericpgreen** [comment]
I believe the issue was a bit localized. My real field is named something like `object1.nestedObject1:something`, so I was wrapping the nested name in backticks.

```
object1.`nestedObject1:something`
```

Removing the backticks worked, so there is no issue.

**Comment by sarahollis123** [comment]
Hi Eric,
I am having the same issue , I was wondering if you could post an example of your solution here?

**Comment by ericpgreen** [comment]
For me just removing the backticks did the trick:

`object1.nestedObject1:something`

**Comment by sarahollis123** [comment]
I am able to extract the field properly for a nested field just on the
second level (as your example above) but not for further nested fields i.e.
object1.nestedObject1.nestednestedObject1:something,
For those fields (nestednestedObject1), I get just the second level that is
brought back (object1.nestedObject1), with list() as the response that
appears.
Any ideas?
*---------------------------------------------------*
*Sara Hollis, MSc*
Emergency, Trauma and Acute Care Programme
World Health Organization
Geneva, Switzerland

Whatsapp +1 281 300 7209
Mobile +41 78 247 4807

**Comment by ericpgreen** [comment]
Hopefully someone else can weigh in. I have a pretty loose grasp of json.
