### ISSUE TITLE
Allow to pass literal JSON string

### ISSUE THREAD

**Issue by ColinFay** [jeroen/mongolite#185]
Hello, 

When I do things in Mongo, I'll first try to write my query in MongoDB Compass with the cli. So, in literal JSON. 

When I get back to R, I can't pass this very same string to `mongo$find()`. 

Here's a reprex: 

``` r
library(mongolite)
con <- mongo()
con$insert(
  list(
    name = "colin"
  )
)
#> List of 6
#>  $ nInserted  : int 1
#>  $ nMatched   : int 0
#>  $ nModified  : int 0
#>  $ nRemoved   : int 0
#>  $ nUpserted  : int 0
#>  $ writeErrors: list()
con$find("{'name' : 'colin'}")
#> Error: Invalid JSON object: {'name' : 'colin'}
```

<sup>Created on 2019-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This works in CLI / compass: 

![Screenshot 2019-10-03 at 12 11 14](https://user-images.githubusercontent.com/17936236/66118539-eb013e00-e5d6-11e9-9332-0b0e933ac0cf.png)

As far as I see, it's due to the fact that `{jsonlite}` is unable to convert the string to JSON. 

I wonder if we could have something like `con$find("{'name' : 'colin'}", literal = TRUE)` to be able to do that?

**Comment by jeroen** [comment]
The problem is that your query string is invalid JSON because json only accept double quotes and you are using single quotes. Perhaps Compass is a bit more lenient, but in jsonlite you need to use proper json!

Can you try this:

```r
con$find('{"name" : "colin"}')
```

**Comment by ColinFay** [comment]
Ah, indeed, that does work.  

Thanks for the answer! 
Closing then.
