### ISSUE TITLE
ObjectId - timestamp converter

### ISSUE THREAD

**Issue by fmmattioni** [jeroen/mongolite#212]
Is it possible to convert the `ObjectId` to a timestamp with `mongolite`?

Reference here: https://docs.mongodb.com/manual/reference/method/ObjectId.getTimestamp/

**Comment by jeroen** [comment]
@kevinAlbs @rcsanchez97 is it possible to do this with mongo-c-driver?

**Comment by jeroen** [comment]
@fmmattioni the first 4 bytes of the oid contain the timestamp. So you can convert easily convert it in R like so:

```r
oid_to_timestamp <- function(oid){
  val <- strtoi(paste0('0x', substring(oid, 1, 8)))
  structure(val, class = c("POSIXct", "POSIXt"))
}

oid_to_timestamp('5349b4ddd2781d08c09890f3')
```
