### ISSUE TITLE
Adding a few admin features

### ISSUE THREAD

**Issue by vipulg13** [jeroen/mongolite#215]
Dear Team,

first of all, thanks for this package!

I have a requirement in my project where I need to get the list of available databases and collections. Could you please incorporate listDatabases and listCollections methods into this package?

**Comment by jeroen** [comment]
Did you try running the raw command using `con$run()` ?

**Comment by vipulg13** [comment]
hello @jeroen, thanks for your reply. It worked! I somehow missed the "run" method to run any raw command.
