### ISSUE TITLE
Simplify JSON as Argument in Functions 

### ISSUE THREAD

**Issue by herrseverin** [jeroen/mongolite#216]
Hey, first of all, thank you for the extremely helpful package. One question please: I have extremely nested documents. Inside the find function there is obviously a JSON to Data.frame command taking place (I guess jsonlite:::simplify or something?). The result is unfortunately more cumbersome for me to handle than if I would just get back a nested list. Which I then have to deal with using pluck. Would it be possible to control simplify via an argument? `simplifyVector = FALSE` does not work. I tried something like `x = fromJSON(toJSON(x),simplifyVector = FALSE)` but this truly shuffled my data, so thats unusable. All the best, stay healthy!

**Comment by jeroen** [comment]
The quickest way to do that is to use `iterate()` see section 3.5 of https://jeroen.github.io/mongolite/query-data.html#iterating

**Comment by herrseverin** [comment]
Thank you very much. Just tried. This is what I was looking for. I didn't realize that iterate > batch/one returns a list. Sorry, please.
