### ISSUE TITLE
"No suitable servers found" with version 2.4.0

### ISSUE THREAD

**Issue by fdetsch** [jeroen/mongolite#230]
I have a MongoDB sitting on a remote (corporate) server that I contact via `mongo()`. Until package version 2.3.1, everything worked as expected:

```r
con = mongo(
  db = "test"
  , url = "mongodb://x.xxx.xx.xxx:5432/admin
)

con$count()
# 0
```

However, after updating to the newly released version 2.4.0, this suddenly fails with

> Error: No suitable servers found (`serverSelectionTryOnce` set): [TLS handshake failed: error:00000000:lib(0):func(0):reason(0) calling hello on 'x.xxx.xx.xxx:5432']

Has anything changed in `ssl_options()` or in some other place that I now need to consider? Rolling back the package version to 2.3.1 fixes the problem, so I assume this must be somehow related to the latest update.

Let me know if you require additional details.

**Comment by jeroen** [comment]
Yes I am sorry I introduced a bug in the CRAN version. It should be fixed on github, can you try the dev version?

```r
install.packages("mongolite", repos = "https://jeroen.r-universe.dev")
```

**Comment by fdetsch** [comment]
Yeah, this fixes the issue. Thanks!

**Comment by jeroen** [comment]
mongolite 2.4.1 is now on cran. Sorry for the inconvenience
