### ISSUE TITLE
update mongo version? (7.0)

### ISSUE THREAD

**Issue by nedhermann** [jeroen/mongolite#264]
Anyone maintaining this? Would like to use the percentile operator in the current (7.0) version.

[https://www.mongodb.com/docs/manual/release-notes/7.0/#aggregation](https://www.mongodb.com/docs/manual/release-notes/7.0/#aggregation)

**Comment by jeroen** [comment]
Does this require an update of the C driver?

**Comment by nedhermann** [comment]
> Does this require an update of the C driver?

https://www.mongodb.com/docs/languages/c/c-driver/current/

If the driver is <= 1.23, I believe so.

**Comment by jeroen** [comment]
OK I see. I'll try to update it soon then.

**Comment by jeroen** [comment]
I updated it to 1.26.2. You can install the devel version from https://jeroen.r-universe.dev/mongolite. Can you let us know if it works for you?

**Comment by nedhermann** [comment]
No.

Here's an example from [mongo](https://www.mongodb.com/docs/manual/reference/operator/aggregation/percentile/#examples):

```
# connection: test_db

mongo_data <- fromJSON('[
   { "studentId": "2345", "test01": 62, "test02": 81, "test03": 80 },
   { "studentId": "2356", "test01": 60, "test02": 83, "test03": 79 },
   { "studentId": "2358", "test01": 67, "test02": 82, "test03": 78 },
   { "studentId": "2367", "test01": 64, "test02": 72, "test03": 77 },
   { "studentId": "2369", "test01": 60, "test02": 53, "test03": 72 }]')

test_db$insert(mongo_data)

pipeline <- '[
   {
      "$group": {
         "_id": null,
         "test01_percentiles": {
            "$percentile": {
               "input": "$test01",
               "p": [ 0.95 ],
               "method": "approximate"
            }
         }
      }
   }
]'


test_db$aggregate(pipeline)
```

output:
```
Error: unknown group operator '$percentile'
```

**Comment by jeroen** [comment]
That looks like a server error? Are you sure your server runs mongodb 7?

**Comment by jeroen** [comment]
@kevinAlbs @eramongodb do we need to set something in the mongo-c-driver client to enable mongodb-7 APIs?

**Comment by nedhermann** [comment]
@jeroen @kevinAlbs 

Thanks for all the help. Confirming the server is on 7.0 resolved the issue.
Thank's jeroen for the amazingly quick response.

**Comment by jeroen** [comment]
OK well I updated mongolite anyway to mongo-c-driver 2.26.2, even though that turned out to be not the actual problem.
