### ISSUE TITLE
Date format 

### ISSUE THREAD

**Issue by kairos35** [jeroen/mongolite#85]
Hi,
dates in our mongodb are formated as
"start_date" : ISODate("2008-10-08T00:00:00.000Z"),
"end_date" : ISODate("2012-04-06T00:00:00.000Z")

"hen using mongolite to get all the data sets stored under  _data 
 con <- mongo(collection = "a",db = "b", url = "mongodb://cde")
 con$distinct("_data")

dates are presented as numbers:
 -781142400 
-623462400

Is it possible to include a date conversion format in the distinct() query?
Maybe similar to as.POSIXct(con$von_datum,origin = "1970-01-01", tz = "GMT")?

Thanks!

**Comment by jeroen** [comment]
Dupe https://github.com/jeroen/mongolite/issues/81

**Comment by jeroen** [comment]
This should be fixed by updating to jsonlite 1.4:

```r
devtools::install_github("jeroen/jsonlite")
```

**Comment by kairos35** [comment]
Brilliant - thanks a million!
