### ISSUE TITLE
How to "show databases" and "show collections" ?

### ISSUE THREAD

**Issue by kingsnakexxx** [jeroen/mongolite#86]
mongolite is very good, but i need to do more with it. How can i implement these functions, such as "show dabases" and "show collections"?

**Comment by jeroen** [comment]
We don't have that (yet). Currently mongolite is focused on getting data in and out of R, not so much database management. We might add it later though.

**Comment by spsaaibi** [comment]
Hi jeroen. This feature could be extremely helpful for common data science or ml workflows (e.g. one needs to evaluate if a new collection has been created in order to update an ETL process or model).

Thanks for the awesome work with mongolite!

**Comment by deyanspasovlg** [comment]
+1 for the feature.

**Comment by peikert** [comment]
+1 for the feature.

**Comment by jeroen** [comment]
The new version has a `run()` method to run arbitrary methods. I have added a [new chapter](https://jeroen.github.io/mongolite/server-tools.html#running-commands) to the mongolite book with an example how to list collections.

**Comment by SymbolixAU** [comment]
This is a good feature. 

My only concern is you still have to define a `collection` to connect to (even if it's the default "test", or even one which doesn't exist, in the `mongo()` call. 
I suppose in practice this isn't a big deal, but something's nagging that this isn't quite right.
