### ISSUE TITLE
Insert ObjectID in database

### ISSUE THREAD

**Issue by LauraPalas** [jeroen/mongolite#87]
Hi,

I would like to insert some rows in my database and they should include the ID in the format ObjectId.
In order to convert my string to the format ObjectID, I use this:
library(jsonlite)
id <- "eb34c5a2dd617c39a8555288"
a<-toJSON(list("_id" = list("$oid" = unbox(id))))

However, I'm not able to convert "a" to a data frame (which is the input needed for mongo$insert). This is the error that it gives me:
> data.frame(a)
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ""json"" to a data.frame

So how can I insert an element in ObjectId format to the database?

Thank you very much

**Comment by jeroen** [comment]
Did you resolve this issue? If so can you let us know what you for future reference?

**Comment by Percayso-Neil** [comment]
Hi Laura, can you confirm the exact code you executed was.
I'm running something along the lines of (my data frame is much more complex that this illustration):
a=data.frame(newid="eb34c5a2dd617c39a8555288", name="Smith", stringsAsFactors = F)
con$insert(a)

I'd like newid to be stored as an ObjectId, primarily so it can be used in a mongodb lookup against another existing ObjectId.
I've tried various combinations of replace/update/set/convert etc.  whilst these work in general via mongolite, none of them appear to be able to be used to load a data frame with an id as a string and then covert it to and ObjectId.

**Comment by ComeMaes** [comment]
Hi @LauraPalas, @jeroen ,

Thanks for the input, I'm looking at something that seems similar: my use case uses document references, i.e. a document in some collection referencing ("pointing") to another document(s) in another collection by its ObjectId. 
Therefore when I insert a document, I would like to create a field that has the ObjectId format. Unfortunately I've tried different syntax options based on this thread, but none have worked out so far. 
Any ideas how to do this?
Thanks!
