### ISSUE TITLE
running the nested query gives error

### ISSUE THREAD

**Issue by INDER4ALL** [jeroen/mongolite#89]
I have the following query . how can i use this using mongolite.
db.respondent_answers.aggregate([{ "$match": { "test_stamp": "CMIFED-147299235531043", "item_stamp": "147299253431045", "respondent_identity": { "$in": db.respondent_answers.distinct("respondent_identity", { "item_stamp": "147299253431045", "answers.score": { "$in": [3, 1] } }) } } }])

**Comment by jeroen** [comment]
What did you try?

```r
m <- monogo("respondent_answers")
m$aggregate('[{ "$match": { "test_stamp": "CMIFED-147299235531043", "item_stamp": "147299253431045", "respondent_identity": { "$in": db.respondent_answers.distinct("respondent_identity", { "item_stamp": "147299253431045", "answers.score": { "$in": [3, 1] } }) } } }]')
```

**Comment by INDER4ALL** [comment]
I am running two queries right now.
Can you please let me know how to use iterate function and convert it to dataframe as find function is very slow.
Thanks for your help
