### ISSUE TITLE
Adding NaN and Infinity values to database

### ISSUE THREAD

**Issue by LauraPalas** [jeroen/mongolite#91]
Hi @jeroen ,

I'm trying to update a field in my database with a NaN value with this code:
`mongo_stats$update('{"user": {"$oid" : "58b011c1d61ac00116e88888"}}', '{"$set": {"hola": NaN}}')`

However, R does not recognize NaN although Mongo does because running this in the command line works just fine:
`db.userstats.update({user: ObjectId("58b011c1d61ac00116e88888")},{"$set":{"hola":NaN}})`

I have also tried it with Infinity (and -Infinity) and it does not work either with mongolite in R, but with mongo it does again.

Please, I would be very grateful if you could help me with this issue because I need to upload NaN and Infinity values in my database and I don't know how.

Thank you very much,
Laura

**Comment by jeroen** [comment]
I think you can use mongo's "extended json" syntax: https://github.com/mongodb/specifications/blob/master/source/extended-json.rst

For example:
```r
mongo_stats$update('{"user": {"$oid" : "58b011c1d61ac00116e88888"}}', '{"$set": {"hola": "SpecialFloat": {
       "$numberDouble": "NaN"
   }}}')
```
