### ISSUE TITLE
db argument only works on localhost

### ISSUE THREAD

**Issue by ManuelaAlmeida** [jeroen/mongolite#94]
I noticed that this syntax doesn't work (works fine when connecting to localhost):

```
con <- mongo("mtcars", "jeroen_test", url = "mongodb://readwrite:test@ds043942.mongolab.com:43942")
Error: Authentication failed.
```
But this works:

```
con <- mongo("mtcars", url = "mongodb://readwrite:test@ds043942.mongolab.com:43942/jeroen_test")
````

Why is this?
Thanks!

**Comment by jeroen** [comment]
This is how mongodb works. You are authenticating against a given database, in this case `jeroen_test`. Therefore you can an authentication failure if you take out the db from the uri.
