### ISSUE TITLE
findAndModify

### ISSUE THREAD

**Issue by achetverikov** [jeroen/mongolite#95]
Is it possible to use findAndModify? (https://docs.mongodb.com/v3.0/reference/method/db.collection.findAndModify/#db.collection.findAndModify) 

It seem to be implemented in mongoc, but I can't find anything about it in the mongolite docs.

**Comment by jeroen** [comment]
Isn't this the same as `mongo$update()`?

**Comment by achetverikov** [comment]
Sorry, it was more than 6 months ago, I'm not using mongolite anymore and I don't remember the details of the question

**Comment by jeroen** [comment]
OK sorry for the delay :)
